// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuocrrpygfcasvvgwnaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1b2NycnB5Z2ZjYXN2dmd3bmFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTM5ODAsImV4cCI6MjA2MDgyOTk4MH0.B9kX4PBgtcjJ1_rGrV24Jg1Ewe50z1dKEhDdM8LM5vw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);